version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    image: my-products-dashboard-rest.local

    ports:
        - 8087:80

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    links:
      - db
  
  db:
    image: mysql:5.7

    ports:
      - 3307:3306

    volumes:
      - .mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: computer@1.6