version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/web.dockerfile
    container_name: my-products-dashboard-web

    ports:
        - 8087:80

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    links:
      - db

  db:
    image: mysql:5.7
    container_name: my-products-dashboard-db

    ports:
      - 3306:3306

    volumes:
      - .db_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
